baseURL = 'https://dhruv34.github.io/'
languageCode = 'en-us'
title = 'Dhruv Adha'
theme = 'hugo-theme-diary'
canonifyURLs = true

[[menu.main]]
name = "Experience"
url = "/experience"
weight = 1

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 2

[[menu.main]]
name = "Reading"
url = "/bookrecs"
weight = 3